### ISSUE TITLE
Fix files.im and zippyshare link

### ISSUE THREAD

**Issue by yasirarism** [zevtyardt/lk21#1]
Zippyshare and files.im bypass doesn't work now

**Comment by zevtyardt** [comment]
can you provide the zippyshare url or files.im in question? or the error that appears (use the `--debug` argument)

**Comment by yasirarism** [comment]
you can try this link https://www74.zippyshare.com/v/k1ApXgui/file.html, https://files.im/98xvnuxlbcq8
When I use this the result is not a direct link only original link because changed algoritm in zippyshare, you can try it to clarify this problem

**Comment by zevtyardt** [comment]
for files.im after I tried it still can be used, and for zippyshare it is true as said there is a change in algorithm
