### ISSUE TITLE
StreamTape Error [Wrong Direct Link]

### ISSUE THREAD

**Issue by X-Gorn** [zevtyardt/lk21#5]
▶ Code : 
import lk21

urlby = 'https://streamtape.com/v/MJ63vvkz36imXWe/Mango_Babymey_Bugil_24_6_2021.mp4'
bypasser = lk21.Bypass()
url = bypasser.bypass_url(urlby)
print(url) 

▶ Output / TraceBack : 
https://2565136607.tapecontent.net/radosgw/GbMkQbxQ71C1ekK/K1HRN8KMIpJ9iT66ZkhAp6u95Rh1LkA3Wph2Kr8kh2xLEbVcGiwvF6q8h9ypk_TvNUiJtT3pqwdySsZtC1wLTPJpeEgQ_d_NrTtmTvHlSaW_OyxMEY1AM2JS4m3F6vgfTww1gSgq0wNTFGWqfv3wDLBwWMWYsPESPZQYOLcLelWjJ9sILdwCPcDxLp9QX9EBZpcifzqbOnGDTDeOhDOO2NVQQsqpuglxexwhl67Mfk5gfhycxTAwSTeaiRoiL6d0HNfWa5BPp_uS_6YwhDJw64MrXn5pTy10GZTsjA/streamtape_do_not_delete.mp4

**Comment by zevtyardt** [comment]
I have fixed the problem due to wrong `token` fetch. now `streamtape` can be bypassed correctly in lk21 version 1.6.0

```bash
$ lk21 --bypass https://streamtape.com/v/MJ63vvkz36imXWe/Mango_Babymey_Bugil_24_6_2021.mp4

  _____     ___  ____    _____    __
 |_   _|   |_  ||_  _|  / ___ `. /  |
   | |       | |_/ /   |_/___) | `| |
   | |   _   |  __'.    .'____.'  | |
  _| |__/ | _| |  \ \_ / /_____  _| |_
 |________||____||____||_______||_____| 1.6.0

Bypass link streamtape.com: https://streamtape...mXWe/Mango_Babymey_Bugil_24_6_2021.mp4
Bypass link streamtape.com: https://streamtape...Dy9XKxR&token=Y8-35FiHLCmO

https://2371755321.tapecontent.net/3vvkz36imXW...fQcQMcLLQLWPd40/Mango+Babymey+Bugil+24_6_2021.mp4
```
