### ISSUE TITLE
:= invalid syntax in google colab

### ISSUE THREAD

**Issue by a0v0** [zevtyardt/lk21#6]
File "/usr/local/lib/python3.7/dist-packages/lk21/lk21.py", line 69
    if (name := soup.find(class_="package-header__name")):
             ^
SyntaxError: invalid syntax

**Comment by zevtyardt** [comment]
it is walrus operator and only available in python version 3.8. you need to upgrade python to version 3.8 or above

**Comment by theDemon92** [comment]
ok
